'use server'

import { createClient } from '@/lib/supabase/server'
import { prisma } from '@/lib/prisma'
import { uploadToDrive } from '@/services/google-drive'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

/**
 * Server Action to handle secure background streaming of volunteer uploads 
 * directly to category-specific Google Drive folders and Supabase metadata maps.
 */
export async function uploadDocumentAction(formData: FormData) {
    let successfullyUploaded = false

    try {
        // 1. Authenticate Request Domain
        const supabase = await createClient()
        const { data: { user }, error: authError } = await supabase.auth.getUser()

        if (authError || !user) {
            throw new Error('Authentication session expired. Please sign in again.')
        }

        // 2. Extract Basic Core Payload Data
        const file = formData.get('file') as File | null
        const title = formData.get('title') as string
        const categoryId = formData.get('categoryId') as string
        const author = formData.get('author') as string || ''

        if (!file || file.size === 0) {
            throw new Error('Payload error: No valid document file found.')
        }

        if (file.type !== 'application/pdf') {
            throw new Error('Validation error: Only native multi-page PDF assets are permitted.')
        }

        // Guard Constraint: Enforce 25MB file ceiling limits
        const MAX_SIZE = 25 * 1024 * 1024
        if (file.size > MAX_SIZE) {
            throw new Error('Payload allocation error: File size cannot exceed 25MB.')
        }

        // 3. Resolve Category Target Name for Dynamic Layout Decisions
        const category = await prisma.category.findUnique({
            where: { id: categoryId },
            select: { id: true, name: true }
        })

        if (!category) {
            throw new Error('Validation error: Selected asset placement category is invalid.')
        }

        // 4. Conditional Extraction for Academic Assets
        const isAcademic = category.name.toLowerCase() === 'academics'

        let departments: string[] = []
        let semester: string | null = null
        let subject: string | null = null

        if (isAcademic) {
            // Parse the JSON string array generated by the checkbox badges
            const departmentsRaw = formData.get('departments') as string
            try {
                departments = departmentsRaw ? JSON.parse(departmentsRaw) : []
            } catch {
                throw new Error('Validation error: Mismatched department configuration array.')
            }

            if (departments.length === 0) {
                throw new Error('Validation error: Please select at least one target department.')
            }

            const semesterRaw = formData.get('semester') as string
            const subjectRaw = formData.get('subject') as string

            if (!semesterRaw || !subjectRaw) {
                throw new Error('Validation error: Missing required institutional curricular fields.')
            }

            semester = semesterRaw.trim().toUpperCase()
            subject = subjectRaw.trim().toUpperCase()
        }

        // 5. Convert Native File Array Buffer into Node.js Buffer Stream Chunk
        const arrayBuffer = await file.arrayBuffer()
        const buffer = Buffer.from(arrayBuffer)

        // 6. Stream Direct to Google Drive Category Folder System
        const driveAsset = await uploadToDrive(
            buffer,
            file.name,
            file.type,
            category.name
        )

        // 7. Map Metadata Localized inside Supabase Postgres Tables
        await prisma.document.create({
            data: {
                title: title.trim(),
                description: `Uploaded directly into ${category.name} collection tracking stream.`,
                departments: departments, // Maps cleanly to your updated String[] schema array
                semester: semester,       // Will be null for Fiction/Non-Fiction
                subject: subject,         // Will be null for Fiction/Non-Fiction
                author: author.trim() || 'Unknown Author',
                driveFileId: driveAsset.fileId,
                driveLink: driveAsset.driveLink,
                previewLink: driveAsset.previewLink,
                size: file.size,
                status: 'PENDING',
                uploadedBy: user.id,
                categoryId: category.id,
            },
        })

        successfullyUploaded = true
        revalidatePath('/library')
        revalidatePath('/')
    } catch (error: unknown) {
        console.error('Fatal Upload Pipeline Action Fault:', (error as Error).message)
        redirect(`/upload?error=${encodeURIComponent((error as Error).message || 'Fatal service failure')}`)
    }

    if (successfullyUploaded) {
        redirect('/library?upload_success=true')
    }
}